pythonqa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    url(r'^', include('qa.urls')),
    url(r'^', include('core.urls')),
]

qa/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),

    url(r'^vote/question/(?P<object_id>\d+)/$',
        views.QuestionVoteView.as_view(), name='qa_question_vote'),

    url(r'^vote/answer/(?P<object_id>\d+)/$',
        views.AnswerVoteView.as_view(), name='qa_answer_vote'),

    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='qa_profile'),

    url('^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    
    url(r'statistics/', views.statistics, name="statistics" ),

]

qa/models.py
from annoying.fields import AutoOneToOneField
from django.conf import settings
from django.db import models
from django.db.models import F
# from django.utils.text import slugify
from uuslug import slugify
from django_markdown.models import MarkdownField
from hitcount.models import HitCountMixin
from taggit.managers import TaggableManager


class UserQAProfile(models.Model):
    """Model class to define a User profile for the app, directly linked
    to the core Django user model."""
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, primary_key=True,
                             on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)

    def modify_reputation(self, added_points):
        """Core function to modify the reputation of the user profile."""
        self.points = F('points') + added_points
        self.save()

    def __str__(self):  # pragma: no cover
        return self.user.username


class Question(models.Model, HitCountMixin):
    """Model class to contain every question in the forum"""
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False, verbose_name='标题')
    description = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = TaggableManager(help_text='')
    reward = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    closed = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
            try:
                points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION']

            except KeyError:
                points = 0

            self.user.userqaprofile.modify_reputation(points)

        self.total_points = self.positive_votes - self.negative_votes
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Answer(models.Model):
    """Model class to contain every answer in the forum and to link it
    to the proper question."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = MarkdownField(verbose_name='填写答案')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        self.total_points = self.positive_votes - self.negative_votes
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']


class VoteParent(models.Model):
    """Abstract model to define the basic elements to every single vote."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    value = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AnswerVote(VoteParent):
    """Model class to contain the votes for the answers."""
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'answer'),)


class QuestionVote(VoteParent):
    """Model class to contain the votes for the questions."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'question'),)


class BaseComment(models.Model):
    """Abstract model to define the basic elements to every single comment."""
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    """Model class to contain the comments for the answers."""
    comment_text = MarkdownField(verbose_name='填写评论')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(AnswerComment, self).save(*args, **kwargs)


class QuestionComment(BaseComment):
    """Model class to contain the comments for the questions."""
    comment_text = models.CharField(max_length=250, verbose_name='填写评论')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(QuestionComment, self).save(*args, **kwargs)

qa/forms.py
from django import forms
from django.conf import settings
from qa.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'description', 'tags']
        help_texts = {
            'title': '标题'
        }
        labels = {
            'title': '标题',
            'description': '描述',
            'tags': '标签'
        }

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)

        try:
            settings.QA_SETTINGS['qa_description_optional']
            self.fields['description'].required = not settings.QA_SETTINGS[
                'qa_description_optional']

        except KeyError:
            pass

qa/templates/qa/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <title>NO.8 问答网 | {% block title %}{% endblock title %}</title>
    <meta charset="UTF-8"/>
    <link rel="icon" type="image/png" href="static/qa/icon.ico">
    <script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery.jqlouds.min.js' %}"></script>
    <!-- <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'> -->
    <!-- <link href='//fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'> -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="{% static 'css/qa.css' %}" rel="stylesheet"/>
    
     <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
 
 <script type="text/javascript" src="{% static 'js/easyBackground-min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" media="screen">

    <style type="text/css">
      body { 
        background-color: #f4fbfd; 
        background-image: url({% static 'img/bg.png' %});
        background-repeat: repeat-x; padding-top: 30px;
      }
    </style>
  </head>
  <body>  
 <nav class="navbar navbar-top" role="navigation" style="z-index: 98">
  <div class="container"> 
    <div class="left-wd" style="position: absolute;padding: 10px;margin-top: -30px;z-index: 100">
      <h2>
          <a href="{% url 'qa_index' %}">
            
            <img width="50px" src="{% static 'img/no8.png' %}" />
               <orange> NO. Eight </orange>
          </a>
          <small></small>
        </h2>
    </div>
    {% block bar_lg %}
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse in" id="top-navbar-1" aria-expanded="true" style="z-index: 99"> 
      <ul class="nav navbar-nav navbar-right" >
        <li><a class="btn " href="/login">登录</a></li> 
        <li><a class="btn " href="/register">注册</a></li> 
        <li><a class="btn " href="/logout">退出登录</a></li>
      </ul>
    </div>
    {% endblock %}
  </div>
 </nav>

<div id="sky" style="height: 10px; position: relative;margin-top:-100px;z-index: 2" class="jqlouds-clouds">
  <img class="jqlouds-cloud" src="{% static 'img/cloud.png' %}" style="height: 24px; width: 56px; position: absolute; bottom: 76.35px; left: 825.27px;">
  <img class="jqlouds-cloud" src="{% static 'img/cloud.png' %}" style="height: 24px; width: 56px; position: absolute; bottom: 76.35px; left: 825.27px;">
  <img class="jqlouds-cloud" src="{% static 'img/cloud.png' %}" style="height: 32px; width: 75px; position: absolute; bottom: 66.12px; left: 296.94px;">
  <img class="jqlouds-cloud blur" src="{% static 'img/cloud.png' %}" style="height: 32px; width: 75px; position: absolute; bottom: 95.11px; left: 350.37px; filter: blur(3px); opacity: 0.7;">
</div> 

    <!-- <div class="topbar"></div> -->
    <div class="container">
      <div class="page-header">
        <div class="btn-group btn-group-sm pull-right" role="group" style="z-index: 111">

        <a class="btn btn-primary pull-right" href="javascript:history.go(-1);">
          <span class="glyphicon glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
           返回
         </a>
      	<a class="btn btn-warning pull-right" href="#search">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
           搜索
         </a>
        <a class="btn btn-danger pull-right " href="{% url 'qa_create_question' %}">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
           提问
         </a>

        </div> 
          <h2>
            <a href="{% url 'qa_index' %}"> 
              <img width="50px" src=""/> 
            </a>
            <small></small>
          </h2>
        </div>
      </div>
    </div>

    <div class="container">
      {% if messages %}
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
      {% endif %}
      {% block content %}

      {% endblock content %}
      <div id="search">
      	<button type="button" class="close">关闭</button>
      	<form method="GET" action="{% url 'qa_search' %}">
      	  <input type="search" value="" name="word" placeholder="在这里输入关键字" />
      	  <input class="btn btn-lg btn-warning" type="submit" value="搜索" />
      	</form> 
      </div> 
    </div>

    <hr>

    <center>
      <a href="http://www.djangoproject.com/">
        <img src="https://www.djangoproject.com/m/img/badges/djangoproject120x25.gif" border="0" alt="A Django project." title="A Django project." /></a> ·
      <a href="https://github.com/swappsco/django-qa/">Github</a> ·
      <a data-toggle="modal" data-target="#apiModal">API</a> ·
      <a href="#">Python1-NO.8 二次开发</a> ·
      <a href="statistics/">Python1-NO.8 统计</a> .
      <small><a href="/admin">管理面板</a></small></center>
    <br/><br/>


    <!-- Modal -->
    <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="APIModal" aria-hidden="true">
      <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> API Access</h4>
	  </div>
	  <div class="modal-body">
            <ul>
              <li>
		<b>问题清单</b>
		<br/>检索问题列表.
		<br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/questions/?format=json</code>
              </li>
              <br/>
              <li>
		<b>用户列表</b>
		<br/>检索用户列表.
		<br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/users/?format=json</code>
              </li>
            </ul>
	  </div>
	  <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">关闭</button>
	  </div>
	</div>
      </div>
    </div>
    {% block js %}
    <script>
      $(function () {
      $('a[href="#search"]').on('click', function(event) {
      event.preventDefault();
      $('#search').addClass('open');
      $('#search > form > input[type="search"]').focus();
      });

      $('#search, #search button.close').on('click keyup', function(event) {
      if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
      $(this).removeClass('open');
      }
      });

      });
    </script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock js %}
    {%block extra_js %}{% endblock extra_js %}
  <script>
    jQuery(function($) { 
       $('#sky').jQlouds({ 
            wind: true     
      }); 
    }); 
  </script>
  </body>
<style type="text/css">#yddContainer{display:block;font-family:Microsoft YaHei;position:relative;width:100%;height:100%;top:-4px;left:-4px;font-size:12px;border:1px solid}#yddTop{display:block;height:22px}#yddTopBorderlr{display:block;position:static;height:17px;padding:2px 28px;line-height:17px;font-size:12px;color:#5079bb;font-weight:bold;border-style:none solid;border-width:1px}#yddTopBorderlr .ydd-sp{position:absolute;top:2px;height:0;overflow:hidden}.ydd-icon{left:5px;width:17px;padding:0px 0px 0px 0px;padding-top:17px;background-position:-16px -44px}.ydd-close{right:5px;width:16px;padding-top:16px;background-position:left -44px}#yddKeyTitle{float:left;text-decoration:none}#yddMiddle{display:block;margin-bottom:10px}.ydd-tabs{display:block;margin:5px 0;padding:0 5px;height:18px;border-bottom:1px solid}.ydd-tab{display:block;float:left;height:18px;margin:0 5px -1px 0;padding:0 4px;line-height:18px;border:1px solid;border-bottom:none}.ydd-trans-container{display:block;line-height:160%}.ydd-trans-container a{text-decoration:none;}#yddBottom{position:absolute;bottom:0;left:0;width:100%;height:22px;line-height:22px;overflow:hidden;background-position:left -22px}.ydd-padding010{padding:0 10px}#yddWrapper{color:#252525;z-index:10001;background:url(chrome-extension://eopjamdnofihpioajgfdikhhbobonhbb/ab20.png);}#yddContainer{background:#fff;border-color:#4b7598}#yddTopBorderlr{border-color:#f0f8fc}#yddWrapper .ydd-sp{background-image:url()}#yddWrapper a,#yddWrapper a:hover,#yddWrapper a:visited{color:#50799b}#yddWrapper .ydd-tabs{color:#959595}.ydd-tabs,.ydd-tab{background:#fff;border-color:#d5e7f3}#yddBottom{color:#363636}#yddWrapper{min-width:250px;max-width:400px;}</style>
</html>

qa/templates/qa/create_answer.html
{% extends 'qa/base.html' %}
{% load django_markdown %}
{% load static %}
{% block title %}回答{% endblock %}

{% block content %}
<div style="text-align:center;margin:50px 0; font:normal 14px/24px 'MicroSoft YaHei';">
  {% if message %}
  <strong>输入有效的问题!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_answer' view.kwargs.question_id %}{% endblock action_url %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success btn-primary btn-lg " type="submit" value="提交答案" />
  </form>
  <script type="text/javascript">

      $(document).ready(function() {
    $('body').easyBackground({
        wrapNeighbours: true
    });
      });

  </script>
</div>


{% endblock content %}
{% block extra_js %}
  {% markdown_editor "#id_answer_text" %}
  {% markdown_media %}
{% endblock %}

qa/templates/qa/detail_question.html
{% extends 'qa/base.html' %}
{% load django_markdown %}
{% load staticfiles %}
{% block title %}问题详细{% endblock %}
{% block bar_lg %}
{% endblock %}

{% block content %}

{% if question.closed %}
  <div class="closed"></div>
{% else %}
    {% if question.reward %}
    <div class="rewarding"></div>
    {% else %}
    <div class="open"></div>
    {% endif %}
{% endif %}


{% if message %}
    <div class="alert alert-danger" role="alert">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% comment %}

{% if question.reward %}
    <div class="alert alert-info" role="alert">这个问题被认为值得 <b>{{ question.reward }}<b> points!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}
{% endcomment %}

<div class="jumbotron">
  <div class="row">
    {% if user.is_authenticated and question.user != user %}
      <div class ="col-sm-1">
        <big class="pull-left custom-big"><b>{{ question.total_points }}</b></big>
      </div>
      <div class ="col-sm-1">
        <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="hidden" name="upvote" value="on">
          <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="投票赞成这个答案"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
        </form>
          <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="投票否决这个答案"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
        </form>
      </div>
    {% endif %}
    <div class="col-sm-10" style="overflow: scroll;">
      <small class="pull-right">发表于 {{ question.user.username }}, {{ question.pub_date }}</small>
      {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa_update_question' question.id %}"><small class="pull-right">编辑 &nbsp;</small></a>{% endif %}
      <h3><cool>Q: </cool>{{ question.title }}</h3>
      <h4>{{ question.description|markdown }}</h4>
      <p>
      {% if question.closed %}
          <p class="pull-right">这个问题已经结束了。</p>
      {% else %}
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_answer' question.id %}" role="button">回答这个问题！</a>
          <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_question_comment' question.id %}" role="button">评论这个问题！</a>
          <form action="{% url 'qa_close_question' question.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}"/>
            <button type="submit" class="btn btn-warning btn-sm pull-right" data-toggle="tooltip" data-placement="bottom">关闭问题</button>
          </form>
      {% endif %}
      </p>
    </div>
  </div>
</div>
{% if last_comments %}
  <h4>评论</h4>
  {% for comment in last_comments %}
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
    <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_question_comment' comment.id %}" class="pull-right"><small>编辑 &nbsp;</small></a>{% endif %}
    </div>
  </div>
  {% endfor %}
{% endif %}
{% if answers %}
  <h3>回答</h3>
  <hr/>

    {% for answer in answers %}
    <div class="row">
      {% if user.is_authenticated and answer.user != user %}
      <div class ="col-md-1">
        <div class="row">
          <div class ="col-sm-1"><big class="pull-left custom-big"><b>{{ answer.total_points }}</b></big></div>
          <div class ="col-sm-1">
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <input type="hidden" name="upvote" value="on">
              <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
          </form>
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button></div>
          </form>
        </div>
      </div>
      {% endif %}
      <div class ="col-md-9">
        <a href="{% url 'qa_create_answer_comment' answer.id %}" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> 评论 &nbsp;</small></a>
        {% if answer.user == user %}<a href="{% url 'qa_update_answer' answer.id %}" class="pull-right"><small>编辑 &nbsp;</small></a>{% endif %}
            <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text|markdown }}</div>
        {% if answer.answercomment_set %}
          {% for comment in answer.answercomment_set.all %}
            <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_answer_comment' comment.id %}" class="pull-right"><small>编辑 &nbsp;</small></a>{% endif %}
          <hr>
          {% endfor %}
        {% endif %}
      </div>
          <div class ="col-md-2">
            {% if answer.user.userqaprofile.picture %}
                <img class="pull-right" src="{{ answer.user.userqaprofile.picture }}">
            {% else %}
                <img class="pull-right" width="50px" height="50px" src="{% static "qa/user.png" %}">
            {% endif %}
            <p class="pull-right">- <b><a href="{% url 'qa_profile' answer.user.id %}">{{ answer.user.username }}</a> ({{ answer.user.userqaprofile.points }})</b></p>
                {% if user.is_authenticated and answer.question.user == user and answer.question.closed == False %}
                    <form action="{% url 'qa_answer_question' answer.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}"/>
                        <button type="submit" class="btn btn-success btn-sm pull-right" data-toggle="tooltip" data-placement="bottom" title="Mark as answer"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>
                    </form>
                {% else %}
                    {% if  answer.answer == True %}
                        <button class="btn btn-success btn-sm pull-right" title="Picked Answer"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button></div>
                    {% endif %}
                {% endif %}
          </div>
    </div>
  <hr>
    {% endfor %}

{% else %}
<img class="pull-right" src="{% static "qa/question.jpg" %}" alt="question"/>
<center><h2>这个问题仍然是开放的, <a href="{% url 'qa_create_answer' question.id %}" role="button">写回答！</a></h2></center>
{% endif %}


{% endblock content %}
{% block extra_js %}
<script src="https://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock extra_js %}

qa/templates/qa/profile.html
{% extends 'qa/base.html' %}
{% load django_markdown %}

{% block content %}
<h2 class="pull-right">积分: {{ user.points }}</h1>
<ul>
  <li><b>网站 :</b> {{ user.website }} </li>
   <li><b>电子邮箱 :</b> {{ user.user.email }} </li>
   <li><b>加入时间 :</b> {{ user.user.date_joined }} </li>
   <li><b>上次登录 :</b> {{ user.user.last_login }} </li>
   <li><b>活跃 :</b> {{ user.user.is_active }} </li>
<ul>

</div>
{% endblock content %}